### ISSUE TITLE
Error in dosetup

### ISSUE THREAD

**Issue by jasonmold** [srodney/sndrizpipe#7]
Traceback (most recent call last):
  File "/Users/jason/git/sndrizpipe/sndrizpipe/sndrizpipe_main.py", line 27, in <module>
    from . import register
ImportError: cannot import name 'register' from '__main__' (/Users/Jason/git/sndrizpipe/sndrizpipe/sndrizpipe_main.py)

**Comment by srodney** [comment]
@jasonmold : thanks for flagging this.   I just did a bunch of changes to the sndrizpipe structure, and didn't document them very well.   The one that's tripping you up here is that I took away the sndrizpipe.py module, and moved it up one level to become __main__.py.   I was fiddling around with the internal structure and didn't want to lose the old sndrizpipe.py, so I left a copy called sndrizpipe_main.py (I should have done a "git stash" or something). 

Would you please try using the __main__.py function as the script for command-line access, and report here if you get the same kind of import error?  

You should be able to invoke it by running python on the containing folder, like this: 

python /Users/Jason/git/sndrizpipe/sndrizpipe 

(for convenience you may want to set up an alias in your .bashrc or .zshrc or whatever)

**Comment by jasonmold** [comment]
It says: can't find '__main__' module

**Comment by srodney** [comment]
Can you clarify how you have installed?   After the recent updates, you may need to clear out old .pyc files and re-do the setup.py install step.

**Comment by jasonmold** [comment]
This is a new laptop so I installed it from scratch with python setup.py install. There were no  previous versions installed.

**Comment by srodney** [comment]
OK.  I think I've figured out a workaround, but I need to learn more about how to do command-line executable python programs before I can do a real solution.  The workaround is:   

**when you install, use "python setup.py --develop"  instead of "--install".**    This makes a python egg that links back to the installation directory.  Its meant to allow you to make changes to the .py modules on the fly, that get picked up when you import into an interactive shell or run a script.   It also seems to work to make it possible for the __main__.py module to do the relative imports successfully.     

Please let me know if this workaround allows you to get it running again. 

I'll keep this issue here until I get a better solution so that the normal --install setup will work properly (suggestions are welcome!)

**Comment by jasonmold** [comment]
This works if I type **python setup.py develop** (not --develop)
However, the script _run_sndriz.sh_ does not work anymore. I need to use **python PATH/sndrizpipe**  which is not a very good solution

**Comment by srodney** [comment]
Better solution finally achieved. See #8
